#!/bin/bash
#SBATCH -p defq
#SBATCH -J JOB
#SBATCH -o /home/st6322041/Git/git/ML/outdir/test.%J
#SBATCH --gres=gpu:1g.10gb:1

source ~/.bashrc
conda activate ML
which python3
cd ~/Git/git/ML
time python3 pipeline.py